### ISSUE TITLE
[v3.11.1+fabric-1.20.1] Invalid entries in json

### ISSUE THREAD

**Issue by theMisterPhD** [TheCSMods/mc-better-stats#122] opened 2024-06-16 04:55 UTC
### What happened?

New update throws errors into console on server start.

00:44:53
Loading Minecraft 1.21 with Fabric Loader 0.15.11
ForkJoinPool-1-worker-3/WARN00:44:53
The mod "betterstats" contains invalid entries in its mod json:
Console00:44:53
- Unsupported root entry "" at line 26 column 4
- Unsupported root entry "" at line 26 column 92
- Unsupported root entry "" at line 28 column 4
- Unsupported root entry "" at line 28 column 24
00:44:53
The mod "tcdcommons" contains invalid entries in its mod json:
Console00:44:53
- Unsupported root entry "" at line 27 column 4
- Unsupported root entry "" at line 27 column 198
- Unsupported root entry "" at line 29 column 4
- Unsupported root entry "" at line 29 column 24

### Steps to reproduce

1. Update BSS to 1.21 Fabric Minecraft
2. Start server
3. BSS and it's dependency contain invalid entries in it's mod json

### Relevant log output or crash report

```shell
00:44:52
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
main/INFO00:44:53
Loading Minecraft 1.21 with Fabric Loader 0.15.11
ForkJoinPool-1-worker-3/WARN00:44:53
The mod "betterstats" contains invalid entries in its mod json:
Console00:44:53
- Unsupported root entry "" at line 26 column 4
- Unsupported root entry "" at line 26 column 92
- Unsupported root entry "" at line 28 column 4
- Unsupported root entry "" at line 28 column 24
ForkJoinPool-1-worker-3/WARN00:44:53
The mod "tcdcommons" contains invalid entries in its mod json:
Console00:44:53
- Unsupported root entry "" at line 27 column 4
- Unsupported root entry "" at line 27 column 198
- Unsupported root entry "" at line 29 column 4
- Unsupported root entry "" at line 29 column 24
|-- fabric-sound-api-v1 1.0.23+6573ed8c90
|-- fabric-transfer-api-v1 5.1.12+b559734490
\-- fabric-transitive-access-wideners-v1 6.0.12+6573ed8c90
- fabric-language-kotlin 1.11.0+kotlin.2.0.0
|-- org_jetbrains_kotlin_kotlin-reflect 2.0.0
|-- org_jetbrains_kotlin_kotlin-stdlib 2.0.0
|-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.0
|-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.0
|-- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0
|-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
|-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
|-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0
|-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
|-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
\-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
- fabricloader 0.15.11
\-- mixinextras 0.3.5
- jamlib 1.0.9+1.21
\-- blue_endless_jankson 1.2.3
- java 21
- justmobheads 7.9
- justplayerheads 4.0
- lithium 0.12.3+git.e61bad1
- luckperms 5.4.131
\-- fabric-permissions-api-v0 0.3.1
- minecraft 1.21
- rightclickharvest 4.2.0+1.21
- silencemobs 3.3
- tcdcommons 3.11+fabric-1.21
- voicechat 1.21-2.5.15
|-- fabric-api-base 0.4.42+6573ed8c90
|-- fabric-command-api-v2 2.2.27+6a6dfa1990
|-- fabric-key-binding-api-v1 1.0.47+0af3f5a790
|-- fabric-lifecycle-events-v1 2.3.9+98a7dbbb90
|-- fabric-networking-api-v1 4.1.0+686dcdce90
\-- fabric-resource-loader-v0 1.1.3+b559734490
main/INFO00:44:54
SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/AMP/Minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
Compatibility level set to JAVA_17
Compatibility level set to JAVA_21
Loaded configuration file for Lithium: 138 options available, 0 override(s) found
main/WARN00:44:54
Error loading class: qouteall/imm_ptl/core/network/PacketRedirection$Payload (java.lang.ClassNotFoundException: qouteall/imm_ptl/core/network/PacketRedirection$Payload)
@Mixin target qouteall.imm_ptl.core.network.PacketRedirection$Payload was not found antixray.fabric.mixins.json:imm_ptl_core.PacketRedirection$PayloadMixin from mod antixray
main/INFO00:44:55
Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
00:45:08
Successfully initialized antixray for fabric
Loading Collective version 7.61.
00:45:09
Initializing JamLib on Fabric
Updated config file at /AMP/Minecraft/config/rightclickharvest.json5
Initializing Right Click Harvest on FABRIC
Compatibility version 18
Loading plugins
Loaded 1 plugin(s)
Initializing plugins
Initialized 1 plugin(s)
Registering events for 'audioplayer'
Initializing 'Better Statistics Screen' as 'BetterStatsServer'.
00:45:10
Initializing 'TCD Commons API' 3.11+fabric-1.21 as 'TCDCommonsServer'.
Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
00:45:13
Loaded 1290 recipes
Loaded 1399 advancements
ForkJoinPool.commonPool-worker-1/INFO00:45:13
Loaded 104 translation keys
main/INFO00:45:14
Applied 0 biome modifications to 0 of 64 new biomes in 2.431 ms
Server thread/INFO00:45:14
__
| |__) LuckPerms v5.4.131
|___ | Running on Fabric - fabric@0.100.1+1.21
Console00:45:14
[04:45:14] [Server thread/INFO]:
Server thread/INFO00:45:14
Loading configuration...
Loading storage provider... [H2]
00:45:15
Loading internal permission managers...
Performing initial data load...
Successfully enabled. (took 1017ms)
Starting minecraft server version 1.21
Loading properties
Default game type: SURVIVAL
Generating keypair
Starting Minecraft server on 192.168.1.96:25565
Using epoll channel type
00:45:16
Preparing level "GIGA"
00:45:20
Preparing start region for dimension minecraft:overworld
Worker-Main-2/INFO00:45:21
Preparing spawn area: 0%
Preparing spawn area: 0%
Preparing spawn area: 0%
Server thread/INFO00:45:22
Time elapsed: 1369 ms
Done (6.164s)! For help, type "help"
Loading audio file name mappings...
BlueMap-Plugin-Loading/INFO00:45:22
Loading BlueMap...
VoiceChatServerThread/INFO00:45:22
Voice chat server started at 192.168.1.96:24454
BlueMap-Plugin-Loading/INFO00:45:22
Loading resources...
00:45:23
Loading textures...
00:45:25
Baking resources...
Resources loaded.
The map 'Nether' has no dimension configured.
Console00:45:25
Assuming world: 'GIGA' and dimension: 'minecraft:the_nether'.
BlueMap-Plugin-Loading/INFO00:45:25
Initializing Storage: 'file' (Type: 'bluemap:file')
Loading map 'nether'...
00:45:26
The map 'End' has no dimension configured.
Console00:45:26
Assuming world: 'GIGA' and dimension: 'minecraft:the_end'.
BlueMap-Plugin-Loading/INFO00:45:26
Loading map 'end'...
The map 'Overworld' has no dimension configured.
Console00:45:26
Assuming world: 'GIGA' and dimension: 'minecraft:overworld'.
BlueMap-Plugin-Loading/INFO00:45:26
Loading map 'overworld'...
00:45:27
WebServer bound to all network interfaces on port 8222
Thread-15/INFO00:45:27
WebServer started.
BlueMap-Plugin-Loading/INFO00:45:27
BlueMap loaded!
```

### Other installed mods

Listed in log output

### Code of Conduct

- [X] I agree that if the issue is regarding a crash, I gave the logs and the crash report.
- [X] I agree that I will be available later for any follow-up questions to help diagnose and resolve the issue.

**Comment by TheCSDev** [comment] 2024-06-16 06:11
Hello, and thanks for the bug report!  
This is a duplicate of #117, as this was an issue ever since `v3.9.7`, and I was aware of it the entire time (hence why I opened the issue there).

The issue current arises due to a technical limitation I do not know how to get around, and due to changes in the Fabric loader's code. In the past, Fabric Loader was not programmed to complain about "invalid" entries being present in `fabric.mod.json` files, but I guess they felt the need to add that eventually, which resulted in this happening here. In reality it's completely harmless other than it being unnecessarily "spammy".

Now as for the reason my mods have "invalid" entries in the first place, it has to do with compiler issues/bugs (cuz yea, the (I assume Fabric) compiler has bugs...), and automation, and this is where the explanation will go a little "technical". So if you're interested in why it happens, you may feel free to continue reading (altho it isn't necessary);

### What exactly happened:
Like I said, this explanation isn't necessary to read, but is here just in case someone's curious. I have left it in issue #117, so anyone can read it from there. You're welcome to go there and read it as well.

Thanks again, and have a great day! As for this issue, I think it's best it be closed, as it is a duplicate.

**Closed** 2024-06-16 06:11 UTC
Labels: Bug
